const OK = 200;
const GENERIC_ERROR = 500;
const NOT_FOUND = 404;
const CART_EMPTY = 10001;

module.exports = {
  OK: OK,
  NOT_FOUND: NOT_FOUND,
  GENERIC_ERROR: GENERIC_ERROR,
  CART_EMPTY: CART_EMPTY
};
